apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appdynamics-operator-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: appdynamics-operator-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operatorServiceAccount }}
    namespace: {{ .Release.Namespace }}