{{ if .Values.installInfraViz -}}
apiVersion: cluster.appdynamics.com/v1alpha1
kind: InfraViz
metadata:
    name: {{ printf "%s-%s" .Release.Name "appdynamics-infraviz" | trunc 63 }}
    namespace: {{ .Release.Namespace }}
spec:
    controllerUrl: {{ required "AppDynamics controller URL is required!" .Values.controllerInfo.url }}
    account: {{ required "AppDynamics controller account is required!" .Values.controllerInfo.account }}
    {{- if eq .Values.infraViz.nodeOS "linux" }}
    image: {{ .Values.imageInfo.machineAgentImage }}:{{ .Values.imageInfo.machineAgentTag }}
    {{- else if eq .Values.infraViz.nodeOS "windows" }}
    imageWin: {{ .Values.imageInfo.machineAgentWinImage }}:{{ .Values.imageInfo.machineAgentWinTag }}
    globalAccount: {{ required "AppDynamics controller global account is required when using machine-agent win image!" .Values.controllerInfo.globalAccount }}
    {{- else if eq .Values.infraViz.nodeOS "all" }}
    image: {{ .Values.imageInfo.machineAgentImage }}:{{ .Values.imageInfo.machineAgentTag }}
    imageWin: {{ .Values.imageInfo.machineAgentWinImage }}:{{ .Values.imageInfo.machineAgentWinTag }}
    globalAccount: {{ required "AppDynamics controller global account is required when using machine-agent win image!" .Values.controllerInfo.globalAccount }}
    {{- end }}
    {{ with .Values.infraViz -}}
    nodeOS: {{ .nodeOS -}}
    {{ if .enableMasters }}
    enableMasters: {{ .enableMasters -}}
    {{- end }}
    {{ if .stdoutLogging -}}
    stdoutLogging: {{ .stdoutLogging -}}
    {{- end }}
    {{ if .enableContainerHostId -}}
    enableContainerHostId: {{ .enableContainerHostId -}}
    {{- end }}
    {{ if .runAsUser -}}
    runAsUser: {{ .runAsUser -}}
    {{- end }}
    {{ if .runAsGroup -}}
    runAsGroup: {{ .runAsGroup -}}
    {{- end }}
    {{ if .fsGroup -}}
    fsGroup: {{ .fsGroup -}}
    {{- end }}
    {{ if .enableServerViz -}}
    enableServerViz: {{ .enableServerViz -}}
    {{- end }}
    {{ if .enableDockerViz -}}
    enableDockerViz: {{ .enableDockerViz -}}
    {{- end }}
    {{- end }}
    {{ if .Values.netViz.enabled -}}
    netVizImage: {{ .Values.imageInfo.netVizImage }}:{{ .Values.imageInfo.netvizTag }}
    netVizPort: {{ .Values.netViz.netVizPort -}}
    {{- end}}
    {{ if .Values.infravizPod.imagePullSecret -}}
    imagePullSecret: {{ .Values.infravizPod.imagePullSecret }}
    {{- end }}
    nodeSelector:
    {{- toYaml .Values.infravizPod.nodeSelector | nindent 6 }}
    priorityClassName:
    {{- toYaml .Values.infravizPod.priorityClassName | nindent 6 }}
    # Tolerations
    tolerations:
    {{- toYaml .Values.infravizPod.tolerations | nindent 6 }}
    # Resources
    resources:
    {{- toYaml .Values.infravizPod.resources | nindent 6 }}
    {{ if .Values.infravizPod.overrideVolumeMounts -}}
    overrideVolumeMounts:
    {{- toYaml .Values.infravizPod.overrideVolumeMounts | nindent 6 }}
    {{ end -}}
    env:
    {{- range $env := .Values.infraViz.env }}
       - name: {{ $env.name }}
         value: {{ $env.value | quote }}
    {{- end }}
{{ end -}}
